# Generated by Django 5.0.1 on 2024-02-01 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbooks',
            name='borrow_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 1, 16, 10, 45, 274334)),
        ),
    ]
